
# This file defines a container environment for running Python code

# defines the base docker image used. -slim specifies a stripped down container.
FROM python:3.11-slim 

# sets the working directory inside the container to /app
WORKDIR /app

# when the container starts, it runs "python student_code.py"
CMD ["python", "student_code.py"]
